### ISSUE TITLE
international shipments handling

### ISSUE THREAD

**Issue by mostafaSYR** [webit-de/dhl-bcs#3]
Hi there,

in order to send international packets, the customs needs to get info about the content of the shipment.
However, there is no place to pass these values , any idea ?!
      'ExportDocument'
                  'invoiceNumber'999999999'/invoiceNumber'
                  'exportType'OTHER'/exportType'
                  'exportTypeDescription'Permanent'/exportTypeDescription'
                  'termsOfTrade'DDU'/termsOfTrade'
                  'placeOfCommital'Bonn'/placeOfCommital'
                  'additionalFee'1.00'/additionalFee'
                  'ExportDocPosition'
                     'description'ExportPositionOne'/description'
                     'countryCodeOrigin'DE'/countryCodeOrigin'
                     'customsTariffNumber'12345678'/customsTariffNumber'
                     'amount'1''/amount'
                     'netWeightInKG'0.20'/netWeightInKG'
                     'customsValue'24.96'/customsValue'
                  '/ExportDocPosition'
               '/ExportDocument''

thanks in advance..

**Comment by aiomaster** [comment]
Hi @mostafaSYR ,
you are right, looking in the latest API-docs it seems, that there were some new things added, like ExportDocument or ReturnReceiver. The gem does not support it at the moment but if you want you can add this.
We would need new models for that and add it to the attr_accessor and the to_soap_hash of the shipment.rb
It should be straight forward.
Do you have access to the latest docs and want to make a pull request for this? I can review and merge that, but can not do it all alone at the moment.
Thanks!

**Comment by mostafaSYR** [comment]
Hello @aiomaster,
thanks for your reposne, Im sorry it took me this long, but its  finally  done, 
could you review the changes: [https://github.com/mostafaSYR/dhl-bcs](url).
thanks in advance!

**Comment by aiomaster** [comment]
Hi @mostafaSYR,
thank you for your work!
I looked at your repository, rebased from my current master, squashed your commits to one single commit and fixed the failing test and some minor stuff like whitespaces and style.
You can have a look at the result.
Before merging it would be cool to have a new section in the README.md how to use this new stuff maybe with a small example.
Do you want to write something?
If everything is fine, I will merge to master and push a new version.
Thanks

**Comment by mostafaSYR** [comment]
Sounds just great, I will.
Thanks again for this awesome gem.

**Comment by mostafaSYR** [comment]
Hey
https://github.com/mostafaSYR/dhl-bcs/blob/master/README.md
this is the read-me file , hope its in production soon :) , .
Thanks

**Comment by aiomaster** [comment]
Thanks and here we go:
https://rubygems.org/gems/dhl-bcs
